version: "3.8"

services:
  webrtc-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: saeedghofrani/webrtc-server:latest
    container_name: webrtc-server
    ports:
      - "3001:3001" # Host:Container
    restart: unless-stopped
    networks:
      - webrtc

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  webrtc:
    driver: bridge
